name: SEN1121
channels:
  - pyviz
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - alabaster=0.7.12
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - astroid=2.11.7
  - atomicwrites=1.4.0
  - attrs=22.1.0
  - autopep8=1.6.0
  - babel=2.11.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.11.1
  - binaryornot=0.4.4
  - black=22.6.0
  - blas=1.0
  - bleach=4.1.0
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - cffi=1.15.1
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - colorama=0.4.6
  - colorcet=3.0.1
  - comm=0.1.2
  - console_shortcut=0.1.1
  - contourpy=1.0.5
  - cookiecutter=1.7.3
  - cryptography=38.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.6
  - docutils=0.18.1
  - entrypoints=0.4
  - ffmpeg=4.2.2
  - flake8=4.0.1
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - holoviews=1.15.4
  - hvplot=0.8.2
  - icu=58.2
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - inflection=0.5.1
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=6.19.2
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jedi=0.18.1
  - jellyfish=0.9.0
  - jinja2=3.1.2
  - jinja2-time=0.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - jupyter_server=1.23.4
  - jupyterlab=3.5.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.5
  - keyring=23.4.0
  - kiwisolver=1.4.4
  - lazy-object-proxy=1.6.0
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mesa=1.1.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - numpydoc=1.5.0
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - panel=0.14.2
  - param=1.12.3
  - paramiko=2.8.1
  - parso=0.8.3
  - pathspec=0.9.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - powershell_shortcut=0.0.1
  - poyo=0.5.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pyct=0.4.8
  - pyct-core=0.4.8
  - pydocstyle=6.1.1
  - pyflakes=2.4.0
  - pygments=2.11.2
  - pylint=2.14.5
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyqtwebengine=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.15
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-lsp-black=1.2.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.5.0
  - python-slugify=5.0.2
  - pytz=2022.7
  - pyviz_comms=2.2.1
  - pywin32=305
  - pywin32-ctypes=0.2.0
  - pywinpty=2.0.2
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.0.3
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - requests=2.28.1
  - rope=0.22.0
  - rtree=0.9.7
  - seaborn=0.12.1
  - send2trash=1.8.0
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.3.3
  - spyder-kernels=2.3.3
  - sqlite=3.40.0
  - terminado=0.17.1
  - text-unidecode=1.3
  - textdistance=4.2.1
  - three-merge=0.1.1
  - tinycss=0.4
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - ujson=5.4.0
  - unidecode=1.2.0
  - urllib3=1.26.13
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - whatthepatch=1.0.2
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.14.1
  - xz=5.2.8
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
